import type {
  AiProvider,
  AiProviderConfig,
  AiRequest,
  AiResult
} from "../types";

const providerLabels: Record<AiProvider, string> = {
  mock: "Mock local assistant",
  "openai-compatible": "OpenAI-compatible API",
  "custom-endpoint": "Custom endpoint",
  "google-style": "Google Translate-style endpoint"
};

export function getProviderOptions() {
  return Object.entries(providerLabels).map(([value, label]) => ({
    value: value as AiProvider,
    label
  }));
}

export function buildAiPrompt(request: AiRequest): string {
  return [
    `Task: ${request.action}`,
    "You are assisting with Chinese-to-English academic manuscript writing.",
    request.styleProfile?.brief
      ? `Reference style brief: ${request.styleProfile.brief}`
      : "Reference style brief: none loaded.",
    request.styleProfile?.phrases.length
      ? `Useful phrases: ${request.styleProfile.phrases.join("; ")}`
      : "",
    request.styleProfile?.terms.length
      ? `Terminology: ${request.styleProfile.terms.join("; ")}`
      : "",
    `Chinese source: ${request.sourceZh}`,
    request.draftEn ? `Current English draft: ${request.draftEn}` : "",
    "Return concise academic English and a short revision note."
  ]
    .filter(Boolean)
    .join("\n");
}

export async function runAiAction(
  config: AiProviderConfig,
  request: AiRequest
): Promise<AiResult> {
  if (config.provider === "mock") {
    return runMockAction(request);
  }

  const endpoint =
    config.provider === "openai-compatible"
      ? config.endpoint ?? "https://api.openai.com/v1/chat/completions"
      : config.endpoint;

  if (!endpoint) {
    throw new Error("Endpoint is required");
  }

  if (!config.apiKey && config.provider === "openai-compatible") {
    throw new Error("API key is required");
  }

  const response = await fetch(endpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...(config.apiKey ? { Authorization: `Bearer ${config.apiKey}` } : {})
    },
    body: JSON.stringify({
      model: config.model,
      messages: [{ role: "user", content: buildAiPrompt(request) }],
      input: buildAiPrompt(request)
    })
  });

  if (!response.ok) {
    throw new Error(`Provider request failed: ${response.status}`);
  }

  const data = await response.json();
  const text =
    data?.choices?.[0]?.message?.content ??
    data?.output_text ??
    data?.text ??
    "";

  return {
    text: String(text).trim(),
    notes: "Generated by selected API provider."
  };
}

function runMockAction(request: AiRequest): AiResult {
  const primaryTerm = request.styleProfile?.terms[0] ?? "the proposed method";
  const sourceSummary = request.sourceZh.replace(/\s+/g, " ").slice(0, 80);

  if (request.action === "polish") {
    return {
      text: `Polished academic version: ${request.draftEn ?? sourceSummary}`,
      notes: "Improved clarity, concision, and academic tone."
    };
  }

  if (request.action === "style-rewrite") {
    return {
      text: `In line with the reference corpus, ${primaryTerm} is presented with concise academic phrasing.`,
      notes: "Applied reference-paper style cues."
    };
  }

  if (request.action === "explain") {
    return {
      text: "The revision favors precise terminology, active claims, and compact academic sentence structure.",
      notes: "Explained revision choices."
    };
  }

  return {
    text: `Academic translation: ${sourceSummary}`,
    notes: request.styleProfile?.referenceCount
      ? "Translated with reference-paper terminology cues."
      : "Translated with general academic wording."
  };
}
